### ISSUE TITLE
Endless spinning wheels right after program start

### ISSUE THREAD

**Issue by deeplook** [nwhitehead/pineapple#17] opened 2015-09-09 11:13 UTC
I'm running version 0.5 alpha from the ``Pineapple-0.5-MacOSX.dmg`` on Mac OS X 10.10.4 Yosemite. But after a few seconds I'm always getting a yellow triangle with an exclamation mark in it and a message below saying "There appears to be a problem connecting to the local computation server." For a colleague of mine running 10.10.5 it seems to run fine.

<img width="484" alt="pineapple-error-image" src="https://cloud.githubusercontent.com/assets/1001778/9760349/8a223f96-56f4-11e5-8a7d-49b0771b7b81.png">

**Comment by nwhitehead** [comment] 2015-09-09 14:22
This is usually caused by something else using port 8888, such as a previous run of the normal IPython notebook. Version 0.5 needs to have port 8888 available when it starts or it will have problems.

To get debug output, assuming you installed into Applications you can open up Terminal and run the command:

/Applications/Pineapple.app/Contents/MacOS/Pineapple

You can then see the debugging error messages as it tries to start.

**Comment by deeplook** [comment] 2015-09-10 07:06
That makes a lot of sense. I see it's searching for ports starting with 8888, but not as "randomly" as it claims to do (it always adds 1 to the next port number tried). So, maybe the error message can be improved and/or the port search be really more randomized?

Otherwise this seems to be a very promising app for spreading Python/Jupyter to colleges without having to go through any installation hassles. Thanks!

**Comment by deeplook** [comment] 2015-09-11 08:18
Nethertheless it looks like Pineapple 0.5 alpha has trouble finding a free port, even if there is one available above 8888.

**Comment by nwhitehead** [comment] 2015-09-11 08:24
Yes, the 0.5 version requires port 8888, it can't tell the port is already
used even though jupyter chose a different port. The fix is checked in,
will be in the next release.

**Comment by nwhitehead** [comment] 2015-09-14 19:51
Closing because I believe the issue is fixed, reopen if you see the same problem in later releases.

**Closed by nwhitehead** 2015-09-14 19:51 UTC

**Comment by tdiprima** [comment] 2019-05-17 13:08
Pineapple-0.8.0, Version 3.1.0 - It's looking for a file on startup.  In the case where the last file it read no longer exists, the error occurs.
> "There appears to be a problem connecting to the local computation server."

**Comment by tdiprima** [comment] 2019-05-17 13:20
Hi @nwhitehead, this issue happens again in Pineapple-0.8.0, Version 3.1.0.  It's looking for a file on startup.  If the file doesn't exist, it generates an error.  After that, if you leave the app open and do File> Open, it still gets confused sometimes.
